// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gavinklfong/go-rest-api-demo/endpoint"
	"github.com/gavinklfong/go-rest-api-demo/router"
	"github.com/gavinklfong/go-rest-api-demo/service"
)

// Injectors from wire.go:

func InitializeRouter() *router.Router {
	rateService := service.NewRateService()
	getRateEndpoint := endpoint.NewGetRateEndpoint(rateService)
	bookRateEndpoint := endpoint.NewBookRateEndpoint(rateService)
	routerRouter := router.NewRouter(getRateEndpoint, bookRateEndpoint)
	return routerRouter
}
