// Code generated by mockery v2.53.3. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockForexTradeDealService is an autogenerated mock type for the ForexTradeDealService type
type MockForexTradeDealService struct {
	mock.Mock
}

type MockForexTradeDealService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockForexTradeDealService) EXPECT() *MockForexTradeDealService_Expecter {
	return &MockForexTradeDealService_Expecter{mock: &_m.Mock}
}

// NewMockForexTradeDealService creates a new instance of MockForexTradeDealService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForexTradeDealService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForexTradeDealService {
	mock := &MockForexTradeDealService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
