// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package demo

// Injectors from wire.go:

func initializeServiceA() *ServiceA {
	componentY := NewComponentY()
	componentZ := NewComponentZ()
	serviceA := NewServiceA(componentY, componentZ)
	return serviceA
}
